In [1]:
import sys
# import os
# from os.path import join
# import glob
# from copy import deepcopy

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
# from IPython.display import display, clear_output
from tqdm import tqdm

sys.path.insert(0, "../../ABC-SN/code")
# import abcsn_config
# import abcsn_training
# import data_degrading as dg
# import data_plotting as dplt
# import data_preparation as dp
# import preprocessing

sys.path.insert(0, "../code")
import measure_signal as ms
from unpack_dataset import unpack_dataset

# from icecream import ic
# from importlib import reload

2026-03-16 18:52:59.400323: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-03-16 18:52:59.418719: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-03-16 18:52:59.424602: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-03-16 18:52:59.439077: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-16 18:53:01.017847: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
file_dataset = "../data/forSNR/deprecated_3/dataset_SNRinfo.parquet"
df = pd.read_parquet(file_dataset)
wvl, spectra, df_meta = unpack_dataset(df)

num_spectra = spectra.shape[0]
num_wvl = wvl.shape[0]

In [3]:
wvl.shape, spectra.shape, df_meta.shape

((1024,), (3574, 1024), (3574, 20))

In [4]:
# def expand_sn_name(sn_name):
#     obs_prefix = None
#     obs_year = None
#     obs_suffix = None

#     if sn_name.startswith("sn"):
#         obs_prefix = "sn"
#         sn_name = sn_name.strip(obs_prefix)

#     elif sn_name.startswith("PTF"):
#         obs_prefix = "PTF"
#         sn_name = sn_name.strip(obs_prefix)

#     elif sn_name.startswith("iPTF"):
#         obs_prefix = "iPTF"
#         sn_name = sn_name.strip(obs_prefix)

#     elif sn_name.startswith("LSQ"):
#         obs_prefix = "LSQ"
#         sn_name = sn_name.strip(obs_prefix)

#     elif sn_name[0].isdigit():
#         obs_prefix = "unknown"

#     else:
#         assert False, sn_name


#     digits = []
#     for char in sn_name:
#         digits.append(char.isdigit())
#     char_inds = np.where(digits)[0]
#     obs_year = sn_name[:char_inds[-1]+1]

#     if len(obs_year) == 4:
#         obs_suffix = sn_name[4:]
#         obs_year == int(obs_year)
        
#     elif len(obs_year) == 2:
#         obs_suffix = sn_name[2:]
#         if obs_year[0] in ["0", "1", "2"]:
#             obs_year = f"20{obs_year}"
#         else:
#             obs_year = f"19{obs_year}"

#     return obs_prefix, int(obs_year), obs_suffix.lower()
        

# print(expand_sn_name("sn2008ar"))
# print(expand_sn_name("sn05eq"))
# print(expand_sn_name("17ein"))
# print(expand_sn_name("PTF10vgv"))
# print(expand_sn_name("LSQ14efd"))
# print(expand_sn_name("iPTF13bvn"))
# print(expand_sn_name("sn94ae"))

In [5]:
# def fn(x):
#     obs_prefix, obs_year, obs_suffix = expand_sn_name(x["SN Name"])
    
#     x["name_prefix"] = obs_prefix
#     x["name_year"] = obs_year
#     x["name_suffix"] = obs_suffix
#     return x

# df = df.apply(fn, axis=1)

In [6]:
# df = df.sort_values(
#     ["SN Subtype ID",
#      "name_year",
#      "name_suffix",
#      "Spectral Phase",
#      "Spectrum Cardinality",
#     ]).reset_index(drop=True)

In [7]:
# df.to_parquet("../data/forSNR/dataset_SNRinfo.parquet")

In [8]:
df

,name_prefix,name_year,name_suffix,SN Name,SN Subtype,SN Subtype ID,SN Maintype,SN Maintype ID,Spectral Phase,Spectrum Cardinality,...,9872.21,9885.59,9898.98,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24
0,sn,1981,b,sn1981B,Ia-norm,0,Ia,0,-1.5,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,sn,1981,b,sn1981B,Ia-norm,0,Ia,0,15.4,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,sn,1981,b,sn1981B,Ia-norm,0,Ia,0,18.3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,sn,1981,b,sn1981B,Ia-norm,0,Ia,0,22.3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,sn,1989,b,sn1989B,Ia-norm,0,Ia,0,-7.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn,2006,bp,sn2006bp,IIP,9,II,3,17.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3570,sn,2006,bp,sn2006bp,IIP,9,II,3,20.1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3571,sn,2006,bp,sn2006bp,IIP,9,II,3,25.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3572,sn,2006,bp,sn2006bp,IIP,9,II,3,34.1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3573,sn,2006,bp,sn2006bp,IIP,9,II,3,49.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df["SN Name (deprecated)"] = df["SN Name"]

In [10]:
df["name_prefix 2"] = df["name_prefix"]
df.loc[df["name_prefix"] == "unknown", "name_prefix 2"] = "u"

In [11]:
df["name_prefix 2"].unique()

array(['sn', 'u', 'iPTF', 'PTF', 'LSQ'], dtype=object)

In [12]:
df["SN Name"] = df["name_prefix 2"] + df["name_year"].astype(str) + df["name_suffix"]

In [13]:
df["Spectrum Phase"] = df["Spectral Phase"]
df

,name_prefix,name_year,name_suffix,SN Name,SN Subtype,SN Subtype ID,SN Maintype,SN Maintype ID,Spectral Phase,Spectrum Cardinality,...,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24,SN Name (deprecated),name_prefix 2,Spectrum Phase
0,sn,1981,b,sn1981b,Ia-norm,0,Ia,0,-1.5,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn1981B,sn,-1.5
1,sn,1981,b,sn1981b,Ia-norm,0,Ia,0,15.4,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn1981B,sn,15.4
2,sn,1981,b,sn1981b,Ia-norm,0,Ia,0,18.3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn1981B,sn,18.3
3,sn,1981,b,sn1981b,Ia-norm,0,Ia,0,22.3,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn1981B,sn,22.3
4,sn,1989,b,sn1989b,Ia-norm,0,Ia,0,-7.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn1989B,sn,-7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn,2006,bp,sn2006bp,IIP,9,II,3,17.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn2006bp,sn,17.2
3570,sn,2006,bp,sn2006bp,IIP,9,II,3,20.1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn2006bp,sn,20.1
3571,sn,2006,bp,sn2006bp,IIP,9,II,3,25.2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn2006bp,sn,25.2
3572,sn,2006,bp,sn2006bp,IIP,9,II,3,34.1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn2006bp,sn,34.1
3573,sn,2006,bp,sn2006bp,IIP,9,II,3,49.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,sn2006bp,sn,49.0

In [14]:
df.drop(columns=["name_prefix", "name_year", "name_suffix", "name_prefix 2", "SN Name (deprecated)"], inplace=True)
df

,SN Name,SN Subtype,SN Subtype ID,SN Maintype,SN Maintype ID,Spectral Phase,Spectrum Cardinality,Denoising Parameter,minima_i,searchBlu,...,9885.59,9898.98,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24,Spectrum Phase
0,sn1981b,Ia-norm,0,Ia,0,-1.5,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.5
1,sn1981b,Ia-norm,0,Ia,0,15.4,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.4
2,sn1981b,Ia-norm,0,Ia,0,18.3,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.3
3,sn1981b,Ia-norm,0,Ia,0,22.3,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.3
4,sn1989b,Ia-norm,0,Ia,0,-7.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn2006bp,IIP,9,II,3,17.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.2
3570,sn2006bp,IIP,9,II,3,20.1,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.1
3571,sn2006bp,IIP,9,II,3,25.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.2
3572,sn2006bp,IIP,9,II,3,34.1,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.1
3573,sn2006bp,IIP,9,II,3,49.0,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0

In [15]:
df

,SN Name,SN Subtype,SN Subtype ID,SN Maintype,SN Maintype ID,Spectral Phase,Spectrum Cardinality,Denoising Parameter,minima_i,searchBlu,...,9885.59,9898.98,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24,Spectrum Phase
0,sn1981b,Ia-norm,0,Ia,0,-1.5,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.5
1,sn1981b,Ia-norm,0,Ia,0,15.4,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.4
2,sn1981b,Ia-norm,0,Ia,0,18.3,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.3
3,sn1981b,Ia-norm,0,Ia,0,22.3,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.3
4,sn1989b,Ia-norm,0,Ia,0,-7.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn2006bp,IIP,9,II,3,17.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.2
3570,sn2006bp,IIP,9,II,3,20.1,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.1
3571,sn2006bp,IIP,9,II,3,25.2,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.2
3572,sn2006bp,IIP,9,II,3,34.1,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.1
3573,sn2006bp,IIP,9,II,3,49.0,1,10.0,NaN,500.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0

In [16]:
flux_columns = df.filter(regex="\d+").columns
metadata_columns = df.columns.difference(flux_columns)
metadata_columns

Index(['Denoising Parameter', 'SN Maintype', 'SN Maintype ID', 'SN Name',
       'SN Subtype', 'SN Subtype ID', 'Spectral Phase', 'Spectrum Cardinality',
       'Spectrum Phase', 'maxBlu', 'maxRed', 'minima_i', 'noiseWindowBlu',
       'noiseWindowRed', 'searchBlu', 'searchRed', 'useBlu', 'useRed'],
      dtype='object')

In [17]:
proper_column_ordering = [
    "SN Name",
    "Spectrum Phase",
    "Spectrum Cardinality",
    "SN Subtype",
    "SN Maintype",
    "SN Subtype ID",
    "SN Maintype ID",
    "Denoising Parameter",
    "searchBlu",
    "searchRed",
    "minima_i",
    "maxBlu",
    "maxRed",
    "noiseWindowBlu",
    "noiseWindowRed",
    "useBlu",
    "useRed",
    *flux_columns,
]
df = df[proper_column_ordering]

In [18]:
df

,SN Name,Spectrum Phase,Spectrum Cardinality,SN Subtype,SN Maintype,SN Subtype ID,SN Maintype ID,Denoising Parameter,searchBlu,searchRed,...,9872.21,9885.59,9898.98,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24
0,sn1981b,-1.5,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,sn1981b,15.4,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,sn1981b,18.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,sn1981b,22.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,sn1989b,-7.2,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn2006bp,17.2,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3570,sn2006bp,20.1,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3571,sn2006bp,25.2,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3572,sn2006bp,34.1,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3573,sn2006bp,49.0,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
wvl, spectra, df_meta = unpack_dataset(df)

num_spectra = spectra.shape[0]
num_wvl = wvl.shape[0]
df_meta

,SN Name,Spectrum Phase,Spectrum Cardinality,SN Subtype,SN Maintype,SN Subtype ID,SN Maintype ID,Denoising Parameter,searchBlu,searchRed,minima_i,maxBlu,maxRed,noiseWindowBlu,noiseWindowRed,useBlu,useRed
0,sn1981b,-1.5,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
1,sn1981b,15.4,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
2,sn1981b,18.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
3,sn1981b,22.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
4,sn1989b,-7.2,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn2006bp,17.2,1,IIP,II,9,3,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
3570,sn2006bp,20.1,1,IIP,II,9,3,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
3571,sn2006bp,25.2,1,IIP,II,9,3,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
3572,sn2006bp,34.1,1,IIP,II,9,3,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True
3573,sn2006bp,49.0,1,IIP,II,9,3,10.0,500.0,0.0,NaN,0.0,0.0,100.0,100.0,True,True

In [20]:
SNRobjs = np.empty(num_spectra, dtype=object)
for i in tqdm(range(num_spectra)):
    metadata_i = df_meta.loc[i].copy(deep=True)
    spectrum_i = spectra[i]

    specsnr = ms.SpectrumSNR(
        metadata_i["SN Name"],
        metadata_i["SN Subtype"],
        metadata_i["Spectrum Phase"],
        wvl,
        spectrum_i)
    specsnr.execute_algorithm(metadata_i)
    SNRobjs[i] = specsnr

100%|██████████| 3574/3574 [03:47<00:00, 15.72it/s]

In [21]:
spectra_signal = np.empty_like(spectra)
spectra_noise = np.empty_like(spectra)
spectra_SNR = np.empty(num_spectra)
spectra_S = np.empty(num_spectra)
spectra_N = np.empty(num_spectra)
for i, specsnr in enumerate(tqdm(SNRobjs)):
    spectra_signal[i] = specsnr.signal
    spectra_noise[i] = specsnr.noise
    spectra_SNR[i] = specsnr.SNR
    spectra_S[i] = specsnr.S
    spectra_N[i] = specsnr.N

100%|██████████| 3574/3574 [00:00<00:00, 58667.10it/s]

In [22]:
df_meta.loc[:, "SNR"] = spectra_SNR[...]
df_meta.loc[:, "S (SNR)"] = spectra_S[...]
df_meta.loc[:, "N (SNR)"] = spectra_N[...]

In [23]:
df_meta_signal_copy = df_meta.copy(deep=True)
df_meta_noise_copy = df_meta.copy(deep=True)

df_signal_data = pd.DataFrame(data=spectra_signal, columns=wvl.astype(str))
df_noise_data = pd.DataFrame(data=spectra_noise, columns=wvl.astype(str))

df_signal = pd.concat([df_meta_signal_copy, df_signal_data], axis=1)
df_noise = pd.concat([df_meta_noise_copy, df_noise_data], axis=1)

In [24]:
df["SNR"] = df_meta["SNR"]
df["S (SNR)"] = df_meta["S (SNR)"]
df["N (SNR)"] = df_meta["N (SNR)"]

In [25]:
df

,SN Name,Spectrum Phase,Spectrum Cardinality,SN Subtype,SN Maintype,SN Subtype ID,SN Maintype ID,Denoising Parameter,searchBlu,searchRed,...,9912.39,9925.82,9939.27,9952.73,9966.21,9979.71,9993.24,SNR,S (SNR),N (SNR)
0,sn1981b,-1.5,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1871.524905,10.201020,0.005451
1,sn1981b,15.4,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2098.887305,6.663471,0.003175
2,sn1981b,18.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2239.138885,7.397255,0.003304
3,sn1981b,22.3,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,556.796633,3.159352,0.005674
4,sn1989b,-7.2,1,Ia-norm,Ia,0,0,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1568.676779,8.039676,0.005125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,sn2006bp,17.2,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1909.429755,7.142203,0.003740
3570,sn2006bp,20.1,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,639.508576,7.011980,0.010965
3571,sn2006bp,25.2,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2430.950291,10.546622,0.004338
3572,sn2006bp,34.1,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3897.900603,15.915556,0.004083
3573,sn2006bp,49.0,1,IIP,II,9,3,10.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3369.164172,18.518754,0.005497

In [26]:
proper_column_ordering = [
    "SN Name",
    "Spectrum Phase",
    "Spectrum Cardinality",
    "SN Subtype",
    "SN Maintype",
    "SN Subtype ID",
    "SN Maintype ID",
    "SNR",
    "S (SNR)",
    "N (SNR)",
    "Denoising Parameter",
    "searchBlu",
    "searchRed",
    "minima_i",
    "maxBlu",
    "maxRed",
    "noiseWindowBlu",
    "noiseWindowRed",
    "useBlu",
    "useRed",
    *flux_columns,
]

In [27]:
df = df[proper_column_ordering]

In [28]:
df_signal = df_signal[proper_column_ordering]

In [29]:
df_noise = df_noise[proper_column_ordering]

In [30]:
df.to_parquet("../data/forSNR/dataset.parquet")
df_signal.to_parquet("../data/forSNR/signal.parquet")
df_noise.to_parquet("../data/forSNR/noise.parquet")